insert into public.sector values (1,'Manufacturing',null);
insert into public.sector values (2,'Other',null);
insert into public.sector values (3,'Service',null);
insert into public.sector values (10,'Construction materials',1);
insert into public.sector values (11,'Electronics and Optics',1);
insert into public.sector values (12,'Food and Beverage',1);
insert into public.sector values (121,'Bakery & confectionery products',12);
insert into public.sector values (122,'Beverages',12);
insert into public.sector values (123,'Fish & fish products',12);
insert into public.sector values (124,'Meat & meat products',12);
insert into public.sector values (125,'Milk & dairy products',12);
insert into public.sector values (126,'Other',12);
insert into public.sector values (127,'Sweets & snack food',12);
insert into public.sector values (13,'Furniture',1);
insert into public.sector values (14,'Machinery',1);
insert into public.sector values (15,'Metalworking',1);
insert into public.sector values (16,'Plastic and Rubber',1);
insert into public.sector values (17,'Printing',1);
insert into public.sector values (18,'Textile and Clothing',1);
insert into public.sector values (19,'Wood',1);
insert into public.sector values (21,'Creative industries',2);
insert into public.sector values (22,'Energy technology',2);
insert into public.sector values (23,'Environment',2);
insert into public.sector values (131,'Bathroom/sauna ',13);
insert into public.sector values (132,'Bedroom',13);
insert into public.sector values (133,'Children’s room',13);
insert into public.sector values (134,'Kitchen',13);
insert into public.sector values (135,'Living room',13);
insert into public.sector values (136,'Office',13);
insert into public.sector values (137,'Other (Furniture)',13);
insert into public.sector values (138,'Outdoor',13);
insert into public.sector values (139,'Project furniture',13);
insert into public.sector values (141,'Machinery components',14);
insert into public.sector values (142,'Machinery equipment/tools',14);
insert into public.sector values (143,'Manufacture of machinery',14);
insert into public.sector values (144,'Maritime',14);
insert into public.sector values (1441,'Aluminium and steel workboats',144);
insert into public.sector values (1442,'Boat/Yacht building',144);
insert into public.sector values (1443,'Ship repair and conversion',144);
insert into public.sector values (145,'Metal structures',14);
insert into public.sector values (146,'Other',14);
insert into public.sector values (147,'Repair and maintenance service',14);
insert into public.sector values (151,'Construction of metal structures',15);
insert into public.sector values (152,'Houses and buildings',15);
insert into public.sector values (153,'Metal products',15);
insert into public.sector values (154,'Metal works',15);
insert into public.sector values (1541,'CNC-machining',154);
insert into public.sector values (1542,'Forgings, Fasteners',154);
insert into public.sector values (1543,'Gas, Plasma, Laser cutting',154);
insert into public.sector values (1544,'MIG, TIG, Aluminum welding',154);
insert into public.sector values (161,'Packaging',16);
insert into public.sector values (162,'Plastic goods',16);
insert into public.sector values (163,'Plastic processing technology',16);
insert into public.sector values (164,'Plastic profiles',16);
insert into public.sector values (1631,'Blowing',163);
insert into public.sector values (1632,'Moulding',163);
insert into public.sector values (1633,'Plastics welding and processing',163);
insert into public.sector values (181,'Clothing',18);
insert into public.sector values (182,'Textile',18);
insert into public.sector values (191,'Other (Wood)',19);
insert into public.sector values (192,'Wooden building materials',19);
insert into public.sector values (193,'Wooden houses',19);
insert into public.sector values (31,'Business services',3);
insert into public.sector values (32,'Engineering',3);
insert into public.sector values (33,'Information Technology and Telecommunications',3);
insert into public.sector values (331,'Data processing, Web portals, E-marketing',33);
insert into public.sector values (332,'Programming, Consultancy',33);
insert into public.sector values (333,'Software, Hardware',33);
insert into public.sector values (34,'Tourism',3);
insert into public.sector values (35,'Translation services',3);
insert into public.sector values (36,'Transport and Logistics',3);
insert into public.sector values (361,'Air',36);
insert into public.sector values (362,'Rail',36);
insert into public.sector values (363,'Road',36);
insert into public.sector values (364,'Water',36);

